/** Fix + enrich existing articles: set detailed body_en/body_ar + related links. */
import { readFileSync, existsSync } from 'fs'; import { join } from 'path'
import { createClient } from '@sanity/client'; import { randomUUID } from 'crypto'
const p=join(process.cwd(),'.env.local'); if(existsSync(p)) readFileSync(p,'utf-8').split('\n').filter(l=>l.trim()&&!l.startsWith('#')).forEach(l=>{const i=l.indexOf('=');if(i>0){const k=l.slice(0,i).trim();const v=l.slice(i+1).trim().replace(/^["']|["']$/g,'');if(!process.env[k])process.env[k]=v}})
const c=createClient({projectId:process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,dataset:process.env.NEXT_PUBLIC_SANITY_DATASET||'production',apiVersion:'2024-01-01',useCdn:false,token:process.env.SANITY_API_TOKEN})
const key=()=>`k${randomUUID().replace(/-/g,'').slice(0,10)}`
const b=(t:string,style='normal')=>{const k=key();return{_type:'block',_key:k,style,markDefs:[],children:[{_type:'span',_key:k+'s',text:t,marks:[]}]}}
// arr of [style?, text] — string => normal, ['h2', text] => heading
const body=(items:([string,string]|string)[])=>items.map(it=>Array.isArray(it)?b(it[1],it[0]):b(it))

const DATA:Record<string,{en:any[];ar:any[];rel:string[]}>={
 'article-signature-scent':{rel:['article-layering','article-spring-scents'],
  en:body([['h2','Why a Signature Scent Matters'],'Your signature scent is the invisible accessory you never take off. Long after you have left the room, it lingers — a trace of memory tied to who you are. Finding it is less about chasing the newest launch and more about discovering what truly resonates with you.',['h2','Step 1 — Know the Fragrance Families'],'Most fragrances fall into a handful of families: floral, woody, oriental, fresh and gourmand. Start by noticing which ones you are drawn to. If you love the warmth of vanilla and amber, you lean oriental; if you crave crisp citrus and sea air, fresh is your home.',['h2','Step 2 — Always Test on Skin'],'Paper strips reveal only the opening notes. Your skin chemistry transforms a fragrance over hours, so spray it on your wrist and let it breathe. The same scent can smell entirely different on two people.',['h2','Step 3 — Give It a Full Day'],'A great fragrance evolves — top notes fade, the heart blooms, and the base settles into your skin. Live with it for a full day before deciding. The right one will feel effortless, as if it were always yours.',['h2','Step 4 — Trust Your Instinct'],'Forget the rules and the reviews. The perfect scent is the one that makes you feel most like yourself. When you find it, you will simply know.']),
  ar:body([['h2','لماذا يهمّ العطر المميّز'],'عطرك المميّز هو الإكسسوار الخفي الذي لا تخلعه أبداً. فبعد مغادرتك الغرفة بوقت طويل، يبقى أثره — لمسة من الذاكرة مرتبطة بهويتك. العثور عليه لا يتعلّق بملاحقة الإصدار الأحدث، بل باكتشاف ما يتناغم معك حقاً.',['h2','الخطوة 1 — اعرف عائلات العطور'],'تقع معظم العطور في عدد قليل من العائلات: زهرية، خشبية، شرقية، منعشة، وحلوانية. ابدأ بملاحظة أيها تنجذب إليه. إن كنت تحب دفء الفانيليا والعنبر، فأنت تميل للشرقي؛ وإن كنت تتوق إلى الحمضيات المنعشة وهواء البحر، فالمنعش هو موطنك.',['h2','الخطوة 2 — جرّب دائماً على البشرة'],'تكشف شرائح الورق نوتات الافتتاح فقط. كيمياء بشرتك تحوّل العطر عبر ساعات، فرشّه على معصمك واتركه يتنفّس. قد يختلف العطر نفسه تماماً على شخصين.',['h2','الخطوة 3 — امنحه يوماً كاملاً'],'العطر الرائع يتطوّر — تتلاشى النوتات العليا، ويتفتّح القلب، وتستقرّ القاعدة على بشرتك. عِش معه يوماً كاملاً قبل أن تقرّر. العطر الصحيح سيبدو سلساً، وكأنه كان لك دائماً.',['h2','الخطوة 4 — ثق بحدسك'],'انسَ القواعد والمراجعات. العطر المثالي هو الذي يجعلك تشعر بأنك أنت أكثر من أي وقت. وحين تجده، ستعرف ببساطة.'])},
 'article-layering':{rel:['article-signature-scent','article-atelier-oud'],
  en:body([['h2','What Is Fragrance Layering?'],'Layering is the art of wearing two or more fragrances together to create something uniquely yours. Done well, it adds depth, longevity and a signature no one else can replicate.',['h2','Start with a Base'],'Choose a heavier, long-lasting scent as your foundation — oud, amber or sandalwood work beautifully. This anchors the composition and helps lighter notes last longer.',['h2','Add Brightness on Top'],'Layer a fresher floral or citrus over your base to lift it. A rose or neroli on top of warm sandalwood creates a luminous, elegant contrast.',['h2','The Rules of Thumb'],'Keep notes within the same family for effortless harmony, or deliberately contrast warm and fresh for a bolder statement. Above all, less is more — two well-chosen scents are usually enough. Apply the heavier scent first, then the lighter one on top.',['h2','Make It Your Own'],'There are no mistakes, only discoveries. Experiment until you find a combination that feels unmistakably you.']),
  ar:body([['h2','ما هو تركيب العطور؟'],'التركيب هو فن ارتداء عطرين أو أكثر معاً لخلق شيء خاص بك تماماً. وإذا أُتقن، فإنه يضيف العمق والثبات وتوقيعاً لا يستطيع أحد تقليده.',['h2','ابدأ بقاعدة'],'اختر عطراً أثقل وأطول ثباتاً كأساس — العود أو العنبر أو خشب الصندل تعمل بجمال. هذا يرسّخ التركيبة ويساعد النوتات الأخف على الدوام أطول.',['h2','أضف الإشراق في الأعلى'],'ضع طبقة من الزهور أو الحمضيات المنعشة فوق قاعدتك لرفعها. وردة أو نيرولي فوق خشب الصندل الدافئ يخلق تبايناً مضيئاً وأنيقاً.',['h2','القواعد الأساسية'],'أبقِ النوتات ضمن العائلة نفسها للانسجام السلس، أو قابل عمداً بين الدافئ والمنعش لتصريح أجرأ. وقبل كل شيء، القليل أفضل — عطران مُنتقيان جيداً يكفيان عادةً. ضع العطر الأثقل أولاً، ثم الأخف فوقه.',['h2','اجعله خاصاً بك'],'لا توجد أخطاء، بل اكتشافات فقط. جرّب حتى تجد مزيجاً يبدو أنه أنت بلا شك.'])},
 'article-atelier-oud':{rel:['article-layering','article-signature-scent'],
  en:body([['h2','The Most Precious Wood on Earth'],'Oud — or agarwood — forms only when a wild Aquilaria tree is infected by a particular mould. The tree responds by producing a dark, fragrant resin. This rare process is why genuine oud is among the most valuable raw materials in the world.',['h2','Sourcing with Care'],'We source aged agarwood exclusively from sustainably managed, protected forests. Each piece is graded by hand for its oil content, colour and depth of aroma before it ever reaches our atelier.',['h2','The Patience of Maceration'],'True oud cannot be rushed. We macerate the wood slowly over many months, coaxing out its smoky, leathery, resinous soul. The longer the maceration, the richer and more complex the final scent.',['h2','Hand-Blended, Then Aged Again'],'Every batch is blended by hand and aged a second time before bottling. It is a patient, almost meditative ritual — one that no machine can replicate, and one that gives Elyssa oud its unmistakable signature.']),
  ar:body([['h2','أثمن خشب على الأرض'],'العود — أو خشب العود — يتكوّن فقط عندما تُصاب شجرة الأكيلاريا البرية بفطر معيّن. تستجيب الشجرة بإنتاج راتنج داكن وعطر. هذه العملية النادرة هي سبب كون العود الحقيقي من أثمن المواد الخام في العالم.',['h2','الاستيراد بعناية'],'نستورد خشب العود المُعتّق حصرياً من غابات محمية تُدار باستدامة. تُصنّف كل قطعة يدوياً حسب محتواها من الزيت ولونها وعمق رائحتها قبل أن تصل إلى مشغلنا.',['h2','صبر النقع'],'لا يمكن استعجال العود الحقيقي. ننقع الخشب ببطء عبر أشهر عديدة، مستخرجين روحه الدخانية الجلدية الراتنجية. كلما طال النقع، زادت ثراء وتعقيد العطر النهائي.',['h2','يُمزج يدوياً ثم يُعتّق مجدداً'],'تُمزج كل دفعة يدوياً وتُعتّق مرة ثانية قبل التعبئة. إنه طقس صبور وتأمّلي تقريباً — لا تستطيع أي آلة تكراره، ويمنح عود إليسا توقيعه الذي لا يُخطئ.'])},
 'article-spring-scents':{rel:['article-signature-scent','article-layering'],
  en:body([['h2','Lighten Your Wardrobe'],'As the days grow longer, your fragrance should grow brighter. Spring calls for compositions that feel like a fresh start — luminous florals, dewy greens and crisp citrus. Here are five to carry you through the season.',['h2','1. Néroli Azur'],'A breath of Mediterranean air — neroli and bergamot lifted by a touch of sea salt. Effortless and sunlit.',['h2','2. Fleur de Lumière'],'A sun-drenched floral of Grasse jasmine and peony. Romantic without ever feeling heavy.',['h2','3. Iris Poudré'],'Whisper-soft and powdery, built around rare orris butter. Quiet, sophisticated elegance.',['h2','4. Jasmin Étoilé'],'A luminous bouquet of night-blooming white flowers over creamy sandalwood. Radiant and tender.',['h2','5. Vétiver Sauvage'],'Fresh grapefruit and earthy vetiver — clean, green and endlessly wearable on warm days.',['h2','Embrace the Season'],'Whichever you choose, spring is the moment to lighten up and let your scent breathe.']),
  ar:body([['h2','خفّف خزانتك'],'مع طول النهار، يجب أن يصبح عطرك أكثر إشراقاً. يستدعي الربيع تركيبات تشبه بداية جديدة — زهور مضيئة، وخضرة نديّة، وحمضيات منعشة. إليك خمسة عطور ترافقك طوال الموسم.',['h2','1. نيرولي الأزرق'],'نسمة من هواء المتوسّط — نيرولي وبرغموت يرفعهما لمسة من ملح البحر. سلس ومشمس.',['h2','2. زهرة النور'],'عطر زهري مشمس من ياسمين غراس والفاوانيا. رومانسي دون أن يكون ثقيلاً أبداً.',['h2','3. السوسن المعطّر'],'ناعم كالهمس ومسحوقي، مبني حول زبدة السوسن النادرة. أناقة هادئة وراقية.',['h2','4. ياسمين النجوم'],'باقة مضيئة من الزهور البيضاء المتفتّحة ليلاً فوق خشب الصندل الكريمي. متألق ورقيق.',['h2','5. فيتيفر البري'],'جريب فروت منعش وفيتيفر ترابي — نظيف وأخضر وقابل للارتداء بلا نهاية في الأيام الدافئة.',['h2','احتضن الموسم'],'أياً اخترت، الربيع هو لحظة التخفّف وترك عطرك يتنفّس.'])},
}

;(async()=>{
  const ids=Object.keys(DATA)
  for(const id of ids){
    const d=DATA[id]
    const rel=d.rel.map(r=>({_type:'reference',_ref:r,_key:key()}))
    await c.patch(id).set({body_en:d.en,body_ar:d.ar,relatedArticles:rel}).unset(['content']).commit()
    console.log('✓ enriched:',id)
  }
  console.log('\n✅ Article bodies set (EN + AR) + related links.')
})().catch(e=>{console.error('❌',e.message);process.exit(1)})
